# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Ag Alewerks'
tagline:          'Follow along as Silvia & Barry perfect their breweing and share with friends and followers.'
description:      'The brewing adventures of Silvia & Barry.'
url:              "http://agalewerks.com"
baseurl:          ""

author:
  name:           'Barry Forrest'
  url:            https://twitter.com/bforrest30

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate, jekyll-gist]