# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Ag Alewerks"
tagline:          'Hand crafted ales by Silvia & Barry'
description:      'Follow along as Silvia & Barry perfect their breweing and share with friends and followers.'
url:              http://agalewerks.com
baseurl:          /

author:
  name:           'Barry Forrest'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
