baseURL = "https://agalewerks.com/" 
disqusShortname = "barryforrest" # delete this to disable disqus comments
googleAnalytics = "" 
languageCode = "en-us" 
theme = "minimal" 
title = "Ag Alewerks" 

[params]
accent = "orange" 
author = "Barry Forrest" 
backgroundColor = "white" 
description = "Hand crafted ales by Silvia & Barry" 
font = "Raleway" # should match the name on Google Fonts!
githubUsername = "#" 
highlight = true 
highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"] 
highlightStyle = "default" 
showBorder = true 

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/post/"
weight = 3

[[menu.main]]
name = "Beers"
url = "/beers/"
weight = 3
# [[menu.main]]
# name = "Projects"
# url = "/project/"
# weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
name = "envelope-o"
url = "mailto:brewer@agalewerks.com"
weight = 1

# [[menu.icon]]
# name = "github"
# url = "https://github.com/username/"
# weight = 2

[[menu.icon]]
name = "twitter"
url = "https://twitter.com/agalewerks/"
weight = 3

[[menu.icon]]
name = "instagram"
url = "https://instagram.com/agalewerks/"
weight = 5

[markup.goldmark.renderer]
unsafe = true
